export const vendingActionTypes = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_COINS_LIST: "GET_COINS_LIST",
  INSERT_COIN: "INSERT_COIN",
  LOADING: "LOADING",
  PURCHASE_COMPLETE: "PURCHASE_COMPLETE",
  PURCHASE_ERROR: "PURCHASE_ERROR",
  RETURN_MONEY: "RETURN_MONEY",
  SCREEN_MESSAGE: "SCREEN_MESSAGE",
};
